export const hitch = {
    'results': [{
        'category': 'Science: Computers',
        'type': 'multiple',
        'difficulty': 'hard',
        'question': 'The Harvard architecture for micro-controllers added which additional bus?',
        'correct_answer': 'Instruction',
        'incorrect_answers': ['Address', 'Data', 'Control'],
    }, {
        'category': 'Entertainment: Television',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'Which track by &quot;Massive Attack&quot; is used for the theme of &quot;House&quot;? ',
        'correct_answer': 'Teardrop',
        'incorrect_answers': ['Protection', 'Angel', 'Black Milk'],
    }, {
        'category': 'Entertainment: Film',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'What does TIE stand for in reference to the TIE Fighter in &quot;Star Wars&quot;?',
        'correct_answer': 'Twin Ion Engine',
        'incorrect_answers': ['Twin Iron Engine', 'Twin Intercepter Engine', 'Twin Inception Engine'],
    }, {
        'category': 'Geography',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'What African country has Portuguese as its official language?',
        'correct_answer': 'Mozambique',
        'incorrect_answers': ['Botswana', 'Gabon', 'Togo'],
    }, {
        'category': 'Entertainment: Music',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'EDM record label Monstercat is based in which country?',
        'correct_answer': 'Canada',
        'incorrect_answers': ['United States', 'Australia', 'United Kingdom'],
    }, {
        'category': 'General Knowledge',
        'type': 'boolean',
        'difficulty': 'medium',
        'question': 'Cucumbers are usually more than 90% water.',
        'correct_answer': 'True',
        'incorrect_answers': ['False'],
    }, {
        'category': 'Entertainment: Video Games',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'In PROTOTYPE 2, which of the following abilities\/weapons is NOT obtained by an Evolved?',
        'correct_answer': 'Tendrils',
        'incorrect_answers': ['Blade', 'Bio-Bomb', 'Pack Leader'],
    }, {
        'category': 'Entertainment: Video Games',
        'type': 'multiple',
        'difficulty': 'easy',
        'question': 'How many flagship monsters appear in Monster Hunter Gernerations?',
        'correct_answer': '4',
        'incorrect_answers': ['1', '2', '3'],
    }, {
        'category': 'History',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'Which Las Vegas casino was originally constructed and operated by mobster Bugsy Siegel?',
        'correct_answer': 'The Flamingo',
        'incorrect_answers': ['The MGM Grand', 'The Sands', 'The Sahara'],
    }, {
        'category': 'History',
        'type': 'multiple',
        'difficulty': 'hard',
        'question': 'Which of the following was not one of Joseph Stalin&#039;s ten blows during World War II?',
        'correct_answer': 'Vistula-Oder Offensive',
        'incorrect_answers': ['Crimean Offensive', 'Leningrad-Novgorod Offensive', 'Operation Bagration'],
    }],
};
